[build]
  command = "npm run build"    # The build command for your Single-SPA app
  publish = "dist"             # Directory where the built files are located


[[redirects]]
  from = "/*"                  # Catch-all route for Single-SPA SPA routing
  to = "/index.html"           # Serve index.html for all SPA routes
  status = 200
