[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
for = "/*"
[headers.values]
  Content-Security-Policy = "default-src 'self' https: localhost:*; script-src 'unsafe-inline' 'unsafe-eval' https: localhost:*; connect-src https: localhost:* ws://localhost:*; style-src 'unsafe-inline' https:; img-src 'self' data: https:; object-src 'none';"

[[redirects]]
from = "/*"
to = "/index.html"
status = 200

[[redirects]]
from = "/problems"
to = "/.netlify/functions/problems"
status = 200
